# Generated by Django 5.2 on 2025-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_cover',
            field=models.ImageField(upload_to='book_covers/'),
        ),
    ]
