# Generated by Django 5.2 on 2025-05-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_borrowrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='processed_date',
        ),
    ]
